import type { Alert, Milestone, PlannedOrder, Shipment } from "@/types";
import { getCompanyForContainer } from "@/lib/utils";

// Uncle Bills containers clear through Kampala ICD (Inland Container
// Depot) before reaching the store. Aiwibi Uganda containers go
// straight from inland transport to the store — a real operational
// difference between the two businesses, not just a display choice.
export const ROUTE_STEPS_ICD = [
  "Order Placed",
  "Container Loaded",
  "On the High Seas",
  "Mombasa Port",
  "Enroute to Kampala",
  "At ICD",
  "Arrived at Store",
] as const;

export const ROUTE_STEPS_DIRECT = [
  "Order Placed",
  "Container Loaded",
  "On the High Seas",
  "Mombasa Port",
  "Enroute to Kampala",
  "Arrived at Store",
] as const;

export function getRouteStepsForContainer(containerNumber: string): readonly string[] {
  return getCompanyForContainer(containerNumber) === "Aiwibi Uganda"
    ? ROUTE_STEPS_DIRECT
    : ROUTE_STEPS_ICD;
}

export function buildMilestones(
  steps: readonly string[],
  plans: { planned: string; plannedIso?: string; actual: string | null; duration: string }[],
  currentIndex: number,
  delayed: boolean
): Milestone[] {
  return steps.map((name, i) => {
    let status: Milestone["status"] = "pending";
    if (i < currentIndex) status = "completed";
    else if (i === currentIndex) status = delayed ? "delayed" : "current";
    return {
      id: `m-${i}`,
      order: i + 1,
      name,
      status,
      plannedDate: plans[i].planned,
      plannedDateIso: plans[i].plannedIso,
      actualDate: plans[i].actual,
      durationLabel: plans[i].duration,
    };
  });
}

export const shipments: Shipment[] = [
  {
    id: "s-c32",
    shipmentNumber: "SHP-1032",
    containerNumber: "C32",
    origin: "China",
    destination: "Kampala",
    routeVia: ["China", "Mombasa", "Kampala"],
    shippingLine: "MSC",
    containerSize: "40ft",
    mode: "FCL",
    etd: "2024-04-02",
    eta: "2024-04-25",
    finalEta: "2024-04-30",
    currentStatus: "At ICD",
    currentLocation: "Kampala ICD",
    health: "delayed",
    delayDays: 5,
    customer: "Uncle Bills",
    assignedManager: "David Mwangi",
    position: { lat: 0.3336, lng: 32.6089, label: "Kampala ICD" },
    delayReason:
      "ICD arrival delayed — 5 days behind plan. Due to increased port congestion and customs clearance backlog.",
    delayReportedAt: "2024-04-25 08:45 EAT",
    milestones: buildMilestones(
      ROUTE_STEPS_ICD,
      [
        { planned: "05 Apr", actual: "09 Apr", duration: "7-14 days" },
        { planned: "16 Apr", actual: "16 Apr", duration: "2 days" },
        { planned: "20 Apr", actual: "20 Apr", duration: "35 days" },
        { planned: "25 Apr", actual: "25 Apr", duration: "3 days" },
        { planned: "28 Apr", actual: "28 Apr", duration: "3 days" },
        { planned: "25 Apr", actual: "30 Apr", duration: "1 day" },
        { planned: "26 Apr", actual: null, duration: "1 day" },
      ],
      5,
      true
    ),
  },
  {
    id: "s-c33",
    shipmentNumber: "SHP-1033",
    containerNumber: "C33",
    origin: "China",
    destination: "Kampala",
    routeVia: ["China", "Mombasa", "Kampala"],
    shippingLine: "PIL",
    containerSize: "40ft",
    mode: "FCL",
    etd: "2024-04-01",
    eta: "2024-04-27",
    finalEta: "2024-04-27",
    currentStatus: "Enroute to Kampala",
    currentLocation: "Inland Transport",
    health: "on_time",
    delayDays: 0,
    customer: "Uncle Bills",
    assignedManager: "David Mwangi",
    position: { lat: -1.7, lng: 37.3, label: "Inland Transport" },
    milestones: buildMilestones(
      ROUTE_STEPS_ICD,
      [
        { planned: "04 Apr", actual: "04 Apr", duration: "7-14 days" },
        { planned: "15 Apr", actual: "15 Apr", duration: "2 days" },
        { planned: "19 Apr", actual: "19 Apr", duration: "35 days" },
        { planned: "24 Apr", actual: "24 Apr", duration: "3 days" },
        { planned: "27 Apr", actual: null, duration: "3 days" },
        { planned: "30 Apr", actual: null, duration: "1 day" },
        { planned: "01 May", actual: null, duration: "1 day" },
      ],
      4,
      false
    ),
  },
  {
    id: "s-c34",
    shipmentNumber: "SHP-1034",
    containerNumber: "C34",
    origin: "India",
    destination: "Kampala",
    routeVia: ["India", "Mombasa", "Kampala"],
    shippingLine: "MSC",
    containerSize: "20ft",
    mode: "FCL",
    etd: "2024-04-05",
    eta: "2024-04-21",
    finalEta: "2024-04-23",
    currentStatus: "On the High Seas",
    currentLocation: "Indian Ocean",
    health: "delayed",
    delayDays: 2,
    customer: "Uncle Bills",
    assignedManager: "David Mwangi",
    position: { lat: 8.5, lng: 68.2, label: "Indian Ocean" },
    delayReason:
      "Vessel schedule slipped 2 days at transshipment port. No customer action required yet.",
    delayReportedAt: "2024-04-22 11:20 EAT",
    milestones: buildMilestones(
      ROUTE_STEPS_ICD,
      [
        { planned: "08 Apr", actual: "10 Apr", duration: "7-14 days" },
        { planned: "18 Apr", actual: "19 Apr", duration: "2 days" },
        { planned: "21 Apr", actual: null, duration: "35 days" },
        { planned: "24 Apr", actual: null, duration: "3 days" },
        { planned: "27 Apr", actual: null, duration: "3 days" },
        { planned: "30 Apr", actual: null, duration: "1 day" },
        { planned: "01 May", actual: null, duration: "1 day" },
      ],
      2,
      true
    ),
  },
  {
    id: "s-c35",
    shipmentNumber: "SHP-1035",
    containerNumber: "C35",
    origin: "China",
    destination: "Kampala",
    routeVia: ["China", "Mombasa", "Kampala"],
    shippingLine: "PIL",
    containerSize: "40ft HC",
    mode: "FCL",
    etd: "2024-04-03",
    eta: "2024-04-25",
    finalEta: "2024-04-26",
    currentStatus: "Enroute to Kampala",
    currentLocation: "Inland Transport",
    health: "delayed",
    delayDays: 1,
    customer: "Uncle Bills",
    assignedManager: "David Mwangi",
    position: { lat: -1.2, lng: 36.9, label: "Inland Transport" },
    delayReason: "Border clearance at Malaba took longer than scheduled.",
    delayReportedAt: "2024-04-24 09:05 EAT",
    milestones: buildMilestones(
      ROUTE_STEPS_ICD,
      [
        { planned: "06 Apr", actual: "06 Apr", duration: "7-14 days" },
        { planned: "17 Apr", actual: "17 Apr", duration: "2 days" },
        { planned: "20 Apr", actual: "20 Apr", duration: "35 days" },
        { planned: "25 Apr", actual: "25 Apr", duration: "3 days" },
        { planned: "26 Apr", actual: null, duration: "3 days" },
        { planned: "29 Apr", actual: null, duration: "1 day" },
        { planned: "30 Apr", actual: null, duration: "1 day" },
      ],
      4,
      true
    ),
  },
  {
    id: "s-a13",
    shipmentNumber: "SHP-1013",
    containerNumber: "A13",
    origin: "China",
    destination: "Kampala",
    routeVia: ["China", "Mombasa", "Kampala"],
    shippingLine: "MSC",
    containerSize: "40ft",
    mode: "FCL",
    etd: "2024-03-28",
    eta: "2024-04-24",
    finalEta: "2024-04-24",
    currentStatus: "Arrived at Store",
    currentLocation: "Kampala Store",
    health: "completed",
    delayDays: 0,
    customer: "Aiwibi Uganda",
    assignedManager: "David Mwangi",
    position: { lat: 0.317, lng: 32.582, label: "Kampala Store" },
    // Aiwibi Uganda containers skip Kampala ICD entirely — 6 steps, not 7.
    milestones: buildMilestones(
      ROUTE_STEPS_DIRECT,
      [
        { planned: "01 Apr", actual: "01 Apr", duration: "7-14 days" },
        { planned: "10 Apr", actual: "10 Apr", duration: "2 days" },
        { planned: "13 Apr", actual: "13 Apr", duration: "35 days" },
        { planned: "18 Apr", actual: "18 Apr", duration: "3 days" },
        { planned: "21 Apr", actual: "21 Apr", duration: "3 days" },
        { planned: "24 Apr", actual: "24 Apr", duration: "1 day" },
      ],
      6,
      false
    ),
  },
  {
    id: "s-c36",
    shipmentNumber: "SHP-1036",
    containerNumber: "C36",
    origin: "China",
    destination: "Kampala",
    routeVia: ["China", "Mombasa", "Kampala"],
    shippingLine: "MSC",
    containerSize: "20ft",
    mode: "FCL",
    etd: "2024-04-04",
    eta: "2024-04-29",
    finalEta: "2024-04-29",
    currentStatus: "On the High Seas",
    currentLocation: "Arabian Sea",
    health: "on_time",
    delayDays: 0,
    customer: "Uncle Bills",
    assignedManager: "David Mwangi",
    position: { lat: 14.2, lng: 62.4, label: "Arabian Sea" },
    milestones: buildMilestones(
      ROUTE_STEPS_ICD,
      [
        { planned: "07 Apr", actual: "07 Apr", duration: "7-14 days" },
        { planned: "18 Apr", actual: "18 Apr", duration: "2 days" },
        { planned: "22 Apr", actual: null, duration: "35 days" },
        { planned: "27 Apr", actual: null, duration: "3 days" },
        { planned: "30 Apr", actual: null, duration: "3 days" },
        { planned: "02 May", actual: null, duration: "1 day" },
        { planned: "03 May", actual: null, duration: "1 day" },
      ],
      2,
      false
    ),
  },
  {
    id: "s-c37",
    shipmentNumber: "SHP-1037",
    containerNumber: "C37",
    origin: "China",
    destination: "Kampala",
    routeVia: ["China", "Mombasa", "Kampala"],
    shippingLine: "PIL",
    containerSize: "40ft",
    mode: "FCL",
    etd: "2024-03-20",
    eta: "2024-04-15",
    finalEta: "2024-04-15",
    currentStatus: "Arrived at Store",
    currentLocation: "Kampala Store",
    health: "completed",
    delayDays: 0,
    customer: "Uncle Bills",
    assignedManager: "David Mwangi",
    position: { lat: 0.317, lng: 32.582, label: "Kampala Store" },
    milestones: buildMilestones(
      ROUTE_STEPS_ICD,
      [
        { planned: "24 Mar", actual: "24 Mar", duration: "7-14 days" },
        { planned: "02 Apr", actual: "02 Apr", duration: "2 days" },
        { planned: "05 Apr", actual: "05 Apr", duration: "35 days" },
        { planned: "10 Apr", actual: "10 Apr", duration: "3 days" },
        { planned: "13 Apr", actual: "13 Apr", duration: "3 days" },
        { planned: "14 Apr", actual: "14 Apr", duration: "1 day" },
        { planned: "15 Apr", actual: "15 Apr", duration: "1 day" },
      ],
      7,
      false
    ),
  },
  {
    id: "s-c38",
    shipmentNumber: "SHP-1038",
    containerNumber: "C38",
    origin: "China",
    destination: "Kampala",
    routeVia: ["China", "Mombasa", "Kampala"],
    shippingLine: "MSC",
    containerSize: "40ft",
    mode: "FCL",
    etd: "2024-03-18",
    eta: "2024-04-12",
    finalEta: "2024-04-12",
    currentStatus: "Arrived at Store",
    currentLocation: "Kampala Store",
    health: "completed",
    delayDays: 0,
    customer: "Uncle Bills",
    assignedManager: "David Mwangi",
    position: { lat: 0.317, lng: 32.582, label: "Kampala Store" },
    milestones: buildMilestones(
      ROUTE_STEPS_ICD,
      [
        { planned: "22 Mar", actual: "22 Mar", duration: "7-14 days" },
        { planned: "31 Mar", actual: "31 Mar", duration: "2 days" },
        { planned: "03 Apr", actual: "03 Apr", duration: "35 days" },
        { planned: "08 Apr", actual: "08 Apr", duration: "3 days" },
        { planned: "11 Apr", actual: "11 Apr", duration: "3 days" },
        { planned: "12 Apr", actual: "12 Apr", duration: "1 day" },
        { planned: "12 Apr", actual: "12 Apr", duration: "1 day" },
      ],
      7,
      false
    ),
  },
  {
    id: "s-c39",
    shipmentNumber: "SHP-1039",
    containerNumber: "C39",
    origin: "China",
    destination: "Kampala",
    routeVia: ["China", "Mombasa", "Kampala"],
    shippingLine: "PIL",
    containerSize: "45ft",
    mode: "FCL",
    etd: "2024-04-10",
    eta: "2024-05-04",
    finalEta: "2024-05-04",
    currentStatus: "Container Loaded",
    currentLocation: "Shanghai Port",
    health: "on_time",
    delayDays: 0,
    customer: "Uncle Bills",
    assignedManager: "David Mwangi",
    position: { lat: 30.7, lng: 122.1, label: "Shanghai Port" },
    milestones: buildMilestones(
      ROUTE_STEPS_ICD,
      [
        { planned: "13 Apr", actual: "13 Apr", duration: "7-14 days" },
        { planned: "24 Apr", actual: "24 Apr", duration: "2 days" },
        { planned: "28 Apr", actual: null, duration: "35 days" },
        { planned: "03 May", actual: null, duration: "3 days" },
        { planned: "06 May", actual: null, duration: "3 days" },
        { planned: "08 May", actual: null, duration: "1 day" },
        { planned: "09 May", actual: null, duration: "1 day" },
      ],
      1,
      false
    ),
  },
  {
    id: "s-c40",
    shipmentNumber: "SHP-1040",
    containerNumber: "C40",
    origin: "China",
    destination: "Kampala",
    routeVia: ["China", "Mombasa", "Kampala"],
    shippingLine: "MSC",
    containerSize: "40ft",
    mode: "FCL",
    etd: "2024-04-06",
    eta: "2024-04-30",
    finalEta: "2024-05-02",
    currentStatus: "Mombasa Port",
    currentLocation: "Mombasa Port",
    health: "delayed",
    delayDays: 2,
    customer: "Uncle Bills",
    assignedManager: "David Mwangi",
    position: { lat: -4.05, lng: 39.66, label: "Mombasa Port" },
    delayReason: "Port congestion at Mombasa is holding container handling.",
    delayReportedAt: "2024-04-26 07:40 EAT",
    milestones: buildMilestones(
      ROUTE_STEPS_ICD,
      [
        { planned: "09 Apr", actual: "09 Apr", duration: "7-14 days" },
        { planned: "20 Apr", actual: "20 Apr", duration: "2 days" },
        { planned: "24 Apr", actual: "24 Apr", duration: "35 days" },
        { planned: "27 Apr", actual: null, duration: "3 days" },
        { planned: "30 Apr", actual: null, duration: "3 days" },
        { planned: "02 May", actual: null, duration: "1 day" },
        { planned: "03 May", actual: null, duration: "1 day" },
      ],
      3,
      true
    ),
  },
  {
    id: "s-a14",
    shipmentNumber: "SHP-1014",
    containerNumber: "A14",
    origin: "China",
    destination: "Kampala",
    routeVia: ["China", "Mombasa", "Kampala"],
    shippingLine: "PIL",
    containerSize: "40ft",
    mode: "FCL",
    etd: "2024-04-29",
    eta: "2024-05-24",
    finalEta: "2024-05-27",
    currentStatus: "Order Placed",
    currentLocation: "Guangzhou Warehouse",
    health: "not_started",
    delayDays: 0,
    customer: "Aiwibi Uganda",
    assignedManager: "David Mwangi",
    position: { lat: 23.1, lng: 113.3, label: "Guangzhou Warehouse" },
    // Aiwibi Uganda containers skip Kampala ICD entirely — 6 steps, not 7.
    milestones: buildMilestones(
      ROUTE_STEPS_DIRECT,
      [
        { planned: "27 Apr", actual: null, duration: "7-14 days" },
        { planned: "09 May", actual: null, duration: "2 days" },
        { planned: "13 May", actual: null, duration: "35 days" },
        { planned: "18 May", actual: null, duration: "3 days" },
        { planned: "21 May", actual: null, duration: "3 days" },
        { planned: "25 May", actual: null, duration: "1 day" },
      ],
      0,
      false
    ),
  },
];

export const alerts: Alert[] = [
  {
    id: "al-1",
    severity: "critical",
    shipmentNumber: "C32",
    title: "C32 — ICD arrival delayed",
    description: "Shipment is 5 days behind the planned schedule.",
    timestamp: "25 Apr 2024, 08:45 EAT",
    acknowledged: false,
  },
  {
    id: "al-2",
    severity: "warning",
    shipmentNumber: "C34",
    title: "C34 — Missing update",
    description: "No location update for 2 days.",
    timestamp: "25 Apr 2024, 07:10 EAT",
    acknowledged: false,
  },
  {
    id: "al-3",
    severity: "info",
    shipmentNumber: "A14",
    title: "A14 — ETA changed",
    description: "ETA updated from 25 Apr to 27 May.",
    timestamp: "24 Apr 2024, 16:30 EAT",
    acknowledged: false,
  },
  {
    id: "al-4",
    severity: "warning",
    shipmentNumber: "C40",
    title: "C40 — Port congestion",
    description: "Mombasa handling delay is pushing ETA back by 2 days.",
    timestamp: "26 Apr 2024, 07:40 EAT",
    acknowledged: false,
  },
  {
    id: "al-5",
    severity: "critical",
    shipmentNumber: "C35",
    title: "C35 — Border clearance delay",
    description: "Malaba clearance is running 1 day behind plan.",
    timestamp: "24 Apr 2024, 09:05 EAT",
    acknowledged: true,
  },
];

// Recurring "when should the next order be placed" schedules per
// company. anchorDate is one real occurrence the recurrence is computed
// from (see lib/order-planning.ts) — it doesn't have to be in the
// future. leadTimeDays is how far ahead of the computed due date the
// daily reminder starts showing.
export const plannedOrders: PlannedOrder[] = [
  {
    id: "po-1",
    company: "Uncle Bills",
    frequency: "monthly",
    anchorDate: "2026-09-20",
    leadTimeDays: 7,
    notes: "Standard monthly restock — 3x40ft FCL from Guangzhou.",
    active: true,
  },
  {
    id: "po-2",
    company: "Aiwibi Uganda",
    frequency: "quarterly",
    anchorDate: "2026-10-05",
    leadTimeDays: 10,
    notes: "Quarterly bulk order — confirm warehouse capacity before placing.",
    active: true,
  },
  {
    id: "po-3",
    company: "Uncle Bills",
    frequency: "yearly",
    anchorDate: "2027-01-15",
    leadTimeDays: 14,
    notes: "Annual peak-season order, larger volume than the monthly runs.",
    active: true,
  },
  {
    id: "po-4",
    company: "Aiwibi Uganda",
    frequency: "custom",
    customIntervalDays: 45,
    anchorDate: "2026-09-25",
    leadTimeDays: 5,
    notes: "45-day cycle tied to store sell-through rate.",
    active: true,
  },
];

export const currentUser = {
  id: "u-1",
  fullName: "David Mwangi",
  role: "Logistics Manager" as const,
  status: "approved" as const,
};